Fix Compilation Errors due to Windows Encoding  Issues
frida/frida-core pull request #1122
Opened 2024-11-03 16:16 UTC by JunGe-Y

When I was compiling on windows, I got an error

`'utf-8' codec can't decode byte 0x90 in position 2:  invalid start byte"`
I looked at it because my windows system is gbk encoded, which is the encoding on many windows, and the frida-core compiler script is "utf-8" which caused this error, and when I modified it, the compiler worked fine.

2024-11-03 16:31 UTC, JunGe-Y commented
There are many windows systems that are gbk encoded, but newer systems may already use utf-8 encoding, so I think getting it from the system might be a good choice

2024-11-10 17:05 UTC, oleavr requested changes
Thanks!

2024-11-10 17:05 UTC, oleavr commented on compat/build.py
> +import locale
Imports should be sorted

2024-11-13 08:38 UTC, JunGe-Y commented on compat/build.py
> +import locale
Okay, I'm sorry. I've changed it

2024-11-13 22:55 UTC, merged

2024-11-13 22:56 UTC, oleavr commented
Thanks! :raised_hands: