Initialize CoreFoundation on i/macOS
frida/frida-core pull request #340
Opened 2020-08-29 17:16 UTC by mrmacete

The problem is that `CoreFoundation` must be initialised on the main thread, this means right now it's not possible to use anything depending on it during early instrumentation without crashing - unless we fall into the "legacy" dyld code path, for the presence of `DYLD_INSERT_LIBRARIES` and the second-stage jailbreak "bootstrappers" (for Chimera and Unc0ver) which also depend on CoreFoundation.

This change will call the `__CFInitialize` function if either:

- dyld takes the "modern" code path
- dyld takes the "legacy" code path and the "bootstrappers" aren't there, after loading `libSystem`

It's a bit hacky (I didn't find a way to convince dyld to initialise `CoreFoundation` early in the "modern" path), but - to my tests - on jailbreaks like checkra1n or on macOS it works way better than before.

2020-08-29 17:44 UTC, mrmacete commented
i think i could also add a test case

2020-08-30 09:43 UTC, mrmacete commented
Actually, to do that i should add a labrat with CoreFoundation - what's the easiest way to do that?

The test code is pretty simple, something like:

```javascript
function testCF () {
  const getMainPtr = Module.findExportByName(null, 'CFRunLoopGetMain');
  if (getMainPtr === null) {
    console.log('No CoreFoundation');
    return;
  }

  const getMain = new NativeFunction(getMainPtr, 'pointer', []);
  getMain();
  console.log('OK');
}
```

The behaviour without this PR's change is, when calling `getMain()`:

- on macos it hangs forever
- on iOS with checkra1n it crashes

2020-08-31 08:12 UTC, oleavr requested changes
w00t! 🤘

2020-08-31 08:12 UTC, oleavr commented on src/darwin/frida-helper-backend-glue.m
> +static gboolean find_cf_initialize (const GumModuleDetails * details, gpointer user_data);
```suggestion
static gboolean frida_find_cf_initialize (const GumModuleDetails * details, gpointer user_data);
```

2020-08-31 08:12 UTC, oleavr commented on src/darwin/frida-helper-backend-glue.m
> +  if (strcmp (details->path, CORE_FOUNDATION) == 0)
Let's return early here so we can de-indent the following block.

2020-08-31 08:12 UTC, oleavr commented on src/darwin/frida-helper-backend-glue.m
> +    guint32 temp[1];
```suggestion
    guint32 return_address;
```

2020-09-01 10:15 UTC, mrmacete commented
So i added a test, not 100% sure that's the right way to mess with labrats, though 😅

2020-09-01 17:03 UTC, oleavr requested changes

2020-09-01 17:03 UTC, oleavr commented on src/darwin/frida-helper-backend-glue.m
> +  FridaSpawnInstance * self = user_data;
```suggestion
  FridaSpawnInstance * self = user_data;
  GumDarwinModule * core_foundation;
```

2020-09-01 17:03 UTC, oleavr commented on src/darwin/frida-helper-backend-glue.m
> +      GUM_DARWIN_MODULE_FLAGS_NONE, NULL);
```suggestion
  core_foundation = gum_darwin_module_new_from_memory (CORE_FOUNDATION, self->task, details->range->base_address,
      GUM_DARWIN_MODULE_FLAGS_NONE, NULL);
```

2020-09-01 17:15 UTC, merged

2020-09-01 17:19 UTC, oleavr commented
> So i added a test, not 100% sure that's the right way to mess with labrats, though 😅

(Sorry, I totally forgot to answer your original question about that!)  What you did was great, there's just a manual fix-up process where we for now have to edit `Makefile.macos.mk` and replace `-m32` and `-m64` with `-arch arm64` and `-arch arm64e`, rebuild the binaries, copy them to a subdir, revert them to the originals, and from the subdir run `../merge-macos-slices.sh` – ugh :-)

2020-09-01 17:21 UTC, mrmacete commented
thanks!! copying this in a not for the future!