Check required functions
frida/frida-core pull request #452
Opened 2023-02-10 17:12 UTC by milahu

fix #451 

fail early when required functions are missing

2023-02-10 23:03 UTC, oleavr commented
Thanks! Could you tweak the commit messages slightly:

```
meson: Require usrsctp_get_timeout()
meson: Require Frida fork of GLib
```

(So I can rebase and merge this PR as-is.)

2023-02-11 07:57 UTC, milahu commented
fixed. some checks are still missing, but i can make a new PR

2023-02-16 16:57 UTC, oleavr requested changes
Thanks! One concern:

2023-02-16 16:57 UTC, oleavr commented on meson.build
> +endif
We should support `auto` , so this would be a regression.

2023-02-16 17:25 UTC, oleavr requested changes
Yay!

2023-02-16 17:25 UTC, oleavr commented on meson.build
> +  'please use vala from https://github.com/frida/vala and glib from https://github.com/frida/glib'
```suggestion
  'Please use Vala from https://github.com/frida/vala and GLib from https://github.com/frida/glib'
```

(We could support using vanilla GLib as well, to better integrate with distro packages. That is, for frida-agent/frida-gadget we should use our own fork, but for the rest there's no benefit.)

2023-02-16 17:25 UTC, oleavr commented on meson.build
> +  not_found_message: 'please use glib-networking from https://github.com/frida/glib-networking'
```suggestion
  not_found_message: 'Please use GLib Networking from https://github.com/frida/glib-networking'
```

2023-02-16 17:25 UTC, oleavr commented on meson.build
> +    'please use usrsctp with https://github.com/sctplab/usrsctp/pull/591'
```suggestion
    'Please use usrsctp with https://github.com/sctplab/usrsctp/pull/591'
```

2023-02-16 17:26 UTC, merged

2023-02-17 00:51 UTC, oleavr commented
Afraid I had to revert this as it caused regressions -- when cross-compiling for iOS the `gio_prepare_to_fork` check fails for some reason. That reminds me we desperately need some CI for this repo :sweat_smile: